dist: bionic

before_install:
  - sudo apt-get install -y autoconf-archive autopoint doxygen libgpiod-dev
addons:
  apt:
    update: true

language: c
compiler:
  - clang
  - gcc

script:
  - ./autogen.sh
  - ./configure
  - make
  - make distcheck

after_success:
  - make html

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doxydoc/html/
  github_token: $GITHUB_TOKEN
  keep_history: false
  verbose: true
  on:
    branch: master
